name: LINUX|BUILD
permissions:
  contents: read
  actions: read
  checks: none
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on: 
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/linux_*.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.87.0
          platform_version: 22.04
          toolset: gcc
          arch: x86

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - run: pip install meson ninja

      - run: meson setup --buildtype debug --backend=ninja build --default-library=static
        env:
          BOOST_ROOT: "${{ github.workspace }}/boost/boost"

      - run: meson compile -C build

      - run: tar -zcvf data.tar.gz build meson.build

      - uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.tar.gz
