name: LINUX|TESTS
permissions:
  contents: read
  actions: read
  checks: none
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on: 
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: ${GITHUB_EVENT_PATH} >> ${GITHUB_OUTPUT} 
        id: get_event_json
        run: |
          content=`cat ${GITHUB_EVENT_PATH}`
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "value=${content}" >> ${GITHUB_OUTPUT}

      - run: echo "value="${{ fromJson(steps.get_event_json.outputs.value).workflow_run.id }} >> ${GITHUB_OUTPUT}
        id: get_run_id

      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.value }}
          name: data
          github-token: ${{ secrets.GH_PAT }}

      - run: tar zxvf data.tar.gz

      - run: LDFLAGS=-L$(pwd)/install/lib/x86_64-linux-gnu ./build/test-instance-with-asio
      - run: LDFLAGS=-L$(pwd)/install/lib/x86_64-linux-gnu ./build/test-network
      - run: LDFLAGS=-L$(pwd)/install/lib/x86_64-linux-gnu ./build/test-database
      - run: LDFLAGS=-L$(pwd)/install/lib/x86_64-linux-gnu ./build/test-siege
